/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness
     * @description The process is up. Does not touch dependencies.
     */
    get: operations["health_api_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness
     * @description Checks the dependencies needed for real work. Returns 503 unless all are ``ok``.
     */
    get: operations["ready_api_v1_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/version": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Application and component versions
     * @description Versions of the application and of the libraries that affect results.
     */
    get: operations["get_version_api_v1_version_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CheckStatus
     * @description Status of one readiness check.
     * @enum {string}
     */
    CheckStatus: "ok" | "not_configured" | "unavailable" | "degraded";
    /**
     * ComponentCheck
     * @description Result of one readiness check. ``detail`` never contains credentials.
     */
    ComponentCheck: {
      /** Detail */
      detail?: string | null;
      /** Name */
      name: string;
      status: components["schemas"]["CheckStatus"];
      /** Version */
      version?: string | null;
    };
    /**
     * EmpiricalDistribution
     * @description An empirical distribution given by its samples.
     */
    EmpiricalDistribution: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "empirical";
      /** Samples */
      samples: number[];
    };
    /**
     * FieldError
     * @description One validation error, located by a JSON-pointer-like path.
     */
    FieldError: {
      /**
       * Loc
       * @description Path to the offending field
       */
      loc: (string | number)[];
      /** Msg */
      msg: string;
      /** Type */
      type: string;
    };
    /**
     * HealthResponse
     * @description Liveness: the process is up and serving requests.
     */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
    };
    /**
     * IntervalDistribution
     * @description Known bounds without a stated shape. ``low == high`` is allowed (degenerate).
     */
    IntervalDistribution: {
      /** High */
      high: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "interval";
      /** Low */
      low: number;
    };
    /**
     * LognormalDistribution
     * @description Lognormal given by its median (geometric mean) and geometric standard deviation.
     *
     *     ``ln(X)`` is normal with mean ``ln(median)`` and standard deviation ``ln(gsd)``.
     */
    LognormalDistribution: {
      /** Gsd */
      gsd: number;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "lognormal";
      /** Median */
      median: number;
    };
    /**
     * NormalDistribution
     * @description Normal with mean ``mean`` and standard deviation ``sd``.
     */
    NormalDistribution: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "normal";
      /** Mean */
      mean: number;
      /** Sd */
      sd: number;
    };
    /**
     * PointDistribution
     * @description No stated uncertainty: the quantity's value is used as given.
     */
    PointDistribution: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "point";
    };
    /**
     * ProblemDetail
     * @description Error response body. Never contains stack traces or internal details.
     */
    ProblemDetail: {
      /** Detail */
      detail?: string | null;
      /** Errors */
      errors?: components["schemas"]["FieldError"][];
      /** Instance */
      instance?: string | null;
      /** Request Id */
      request_id?: string | null;
      /** Status */
      status: number;
      /** Title */
      title: string;
      /**
       * Type
       * @description URI identifying the problem type
       * @default about:blank
       */
      type: string;
    };
    /**
     * ProvenanceClass
     * @description The eight provenance classes (PostgreSQL enum ``provenance_class``).
     * @enum {string}
     */
    ProvenanceClass:
      | "OBSERVED"
      | "USER_PROVIDED"
      | "IMPORTED"
      | "DERIVED"
      | "MODELLED"
      | "PREDICTED"
      | "SCENARIO_ASSUMPTION"
      | "SYNTHETIC_DEMO";
    /**
     * QuantityOut
     * @description A quantity as serialized in API responses.
     */
    QuantityOut: {
      provenance: components["schemas"]["ProvenanceClass"];
      /**
       * Result Id
       * @default null
       */
      result_id: string | null;
      /**
       * Source Ref
       * @default null
       */
      source_ref: string | null;
      taint: components["schemas"]["Taint"];
      /**
       * Uncertainty
       * @default null
       */
      uncertainty:
        | (
            | components["schemas"]["PointDistribution"]
            | components["schemas"]["UniformDistribution"]
            | components["schemas"]["TriangularDistribution"]
            | components["schemas"]["NormalDistribution"]
            | components["schemas"]["LognormalDistribution"]
            | components["schemas"]["IntervalDistribution"]
            | components["schemas"]["EmpiricalDistribution"]
          )
        | null;
      /** Unit */
      unit: string;
      /** Value */
      value: number | null;
    };
    /**
     * ReadinessResponse
     * @description Readiness: whether the dependencies needed to serve real work are available.
     */
    ReadinessResponse: {
      /** Checks */
      checks: components["schemas"]["ComponentCheck"][];
      status: components["schemas"]["CheckStatus"];
    };
    /**
     * Taint
     * @description Which kinds of input a value was built on (docs/architecture.md section 10).
     */
    Taint: {
      /**
       * Predicted
       * @default false
       */
      predicted: boolean;
      /**
       * Scenario Assumption
       * @default false
       */
      scenario_assumption: boolean;
      /**
       * Synthetic
       * @default false
       */
      synthetic: boolean;
      /**
       * User Provided
       * @default false
       */
      user_provided: boolean;
    };
    /**
     * TriangularDistribution
     * @description Triangular with lower limit ``min``, mode ``mode`` and upper limit ``max``.
     */
    TriangularDistribution: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "triangular";
      /** Max */
      max: number;
      /** Min */
      min: number;
      /** Mode */
      mode: number;
    };
    /**
     * UniformDistribution
     * @description Uniform between ``min`` and ``max``.
     */
    UniformDistribution: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "uniform";
      /** Max */
      max: number;
      /** Min */
      min: number;
    };
    /**
     * VersionResponse
     * @description Versions of the application and the components that affect results.
     */
    VersionResponse: {
      /** Api Version */
      api_version: string;
      /** Application */
      application: string;
      /** Components */
      components: {
        [key: string]: string;
      };
      /** Environment */
      environment: string;
      /** Git Sha */
      git_sha: string | null;
      /** Python */
      python: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  ready_api_v1_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
      /** @description A dependency is not ready */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessResponse"];
        };
      };
    };
  };
  get_version_api_v1_version_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
    };
  };
}
